<?php

namespace AppBundle\Repository;

/**
 * CoupleImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoupleImageRepository extends \Doctrine\ORM\EntityRepository
{
}
