<?php

namespace AppBundle\Repository;

/**
 * LegendeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegendeRepository extends \Doctrine\ORM\EntityRepository
{
}
