api:
    resource: '.'
    type:     'api_platform'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
app_controllers:
    resource: '@AppBundle/Controller'
    type:     'annotation'